//! Bulk operations for Competency entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCompetencyDto;
use crate::application::service::CompetencyService;
use crate::domain::entity::Competency;

/// Bulk operation handler for Competency entities.
///
/// Wraps `CompetencyService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CompetencyBulkService = GenericBulkService<Competency, CreateCompetencyDto, CompetencyService>;

// <<< CUSTOM
// END CUSTOM
