//! Bulk operations for CourseEnrollment entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCourseEnrollmentDto;
use crate::application::service::CourseEnrollmentService;
use crate::domain::entity::CourseEnrollment;

/// Bulk operation handler for CourseEnrollment entities.
///
/// Wraps `CourseEnrollmentService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CourseEnrollmentBulkService = GenericBulkService<CourseEnrollment, CreateCourseEnrollmentDto, CourseEnrollmentService>;

// <<< CUSTOM
// END CUSTOM
