//! Bulk operations for Course entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCourseDto;
use crate::application::service::CourseService;
use crate::domain::entity::Course;

/// Bulk operation handler for Course entities.
///
/// Wraps `CourseService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CourseBulkService = GenericBulkService<Course, CreateCourseDto, CourseService>;

// <<< CUSTOM
// END CUSTOM
