//! Bulk operations for EmployeeCompetency entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateEmployeeCompetencyDto;
use crate::application::service::EmployeeCompetencyService;
use crate::domain::entity::EmployeeCompetency;

/// Bulk operation handler for EmployeeCompetency entities.
///
/// Wraps `EmployeeCompetencyService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type EmployeeCompetencyBulkService = GenericBulkService<EmployeeCompetency, CreateEmployeeCompetencyDto, EmployeeCompetencyService>;

// <<< CUSTOM
// END CUSTOM
