//! Bulk operations for EmployeeSkill entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateEmployeeSkillDto;
use crate::application::service::EmployeeSkillService;
use crate::domain::entity::EmployeeSkill;

/// Bulk operation handler for EmployeeSkill entities.
///
/// Wraps `EmployeeSkillService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type EmployeeSkillBulkService = GenericBulkService<EmployeeSkill, CreateEmployeeSkillDto, EmployeeSkillService>;

// <<< CUSTOM
// END CUSTOM
