//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod competency_bulk;
pub mod course_bulk;
pub mod course_enrollment_bulk;
pub mod employee_competency_bulk;
pub mod employee_skill_bulk;
pub mod skill_bulk;

pub use competency_bulk::CompetencyBulkService;
pub use course_bulk::CourseBulkService;
pub use course_enrollment_bulk::CourseEnrollmentBulkService;
pub use employee_competency_bulk::EmployeeCompetencyBulkService;
pub use employee_skill_bulk::EmployeeSkillBulkService;
pub use skill_bulk::SkillBulkService;

// <<< CUSTOM
// END CUSTOM
