//! Bulk operations for Skill entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSkillDto;
use crate::application::service::SkillService;
use crate::domain::entity::Skill;

/// Bulk operation handler for Skill entities.
///
/// Wraps `SkillService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SkillBulkService = GenericBulkService<Skill, CreateSkillDto, SkillService>;

// <<< CUSTOM
// END CUSTOM
