//! CourseEnrollment DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::CourseEnrollment;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::EnrollmentStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new CourseEnrollment
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCourseEnrollmentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "course_id")]
    pub course_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    pub status: EnrollmentStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "enrolled_at")]
    pub enrolled_at: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "completed_at")]
    pub completed_at: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub score: Option<Decimal>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a CourseEnrollment
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCourseEnrollmentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "course_id")]
    pub course_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    pub status: EnrollmentStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "enrolled_at")]
    pub enrolled_at: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "completed_at")]
    pub completed_at: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub score: Option<Decimal>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a CourseEnrollment
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCourseEnrollmentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "course_id")]
    pub course_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<EnrollmentStatus>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "enrolled_at")]
    pub enrolled_at: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "completed_at")]
    pub completed_at: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub score: Option<Decimal>,
}

impl PatchCourseEnrollmentDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.course_id.is_some() || self.employee_id.is_some() || self.status.is_some() || self.enrolled_at.is_some() || self.completed_at.is_some() || self.score.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for CourseEnrollment entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CourseEnrollmentResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub course_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    pub status: EnrollmentStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub enrolled_at: NaiveDate,
    pub completed_at: Option<NaiveDate>,
    pub score: Option<Decimal>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for CourseEnrollment entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CourseEnrollmentListResponseDto {
    /// List of items
    pub items: Vec<CourseEnrollmentResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CourseEnrollmentListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CourseEnrollmentResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CourseEnrollmentSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub course_id: Uuid,
    pub employee_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<CourseEnrollment> for CourseEnrollmentResponseDto {
    fn from(entity: CourseEnrollment) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            course_id: entity.course_id,
            employee_id: entity.employee_id,
            status: entity.status,
            enrolled_at: entity.enrolled_at,
            completed_at: entity.completed_at,
            score: entity.score,
            metadata: entity.metadata,
        }
    }
}

impl From<CourseEnrollment> for CourseEnrollmentSummaryDto {
    fn from(entity: CourseEnrollment) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            course_id: entity.course_id,
            employee_id: entity.employee_id,
            created_at,
        }
    }
}

impl From<CreateCourseEnrollmentDto> for CourseEnrollment {
    fn from(dto: CreateCourseEnrollmentDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            course_id: dto.course_id,
            employee_id: dto.employee_id,
            status: dto.status,
            enrolled_at: dto.enrolled_at,
            completed_at: dto.completed_at,
            score: dto.score,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&CourseEnrollment> for CourseEnrollmentResponseDto {
    fn from(entity: &CourseEnrollment) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            course_id: entity.course_id.clone(),
            employee_id: entity.employee_id.clone(),
            status: entity.status.clone(),
            enrolled_at: entity.enrolled_at.clone(),
            completed_at: entity.completed_at.clone(),
            score: entity.score.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCourseEnrollmentDto> for CourseEnrollment {
    fn from_create_dto(dto: CreateCourseEnrollmentDto) -> backbone_core::ServiceResult<Self> {
        Ok(CourseEnrollment::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCourseEnrollmentDto> for CourseEnrollment {
    fn apply_update(mut self, dto: UpdateCourseEnrollmentDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.course_id = dto.course_id;
        self.employee_id = dto.employee_id;
        self.status = dto.status;
        self.enrolled_at = dto.enrolled_at;
        self.completed_at = dto.completed_at;
        self.score = dto.score;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to CourseEnrollment here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

