//! Course DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Course;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::CourseFormat;
use crate::domain::entity::CourseStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Course
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCourseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 180)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub format: CourseFormat,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "duration_hours")]
    pub duration_hours: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 180)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "certification_id")]
    pub certification_id: Option<Uuid>,
    pub status: CourseStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Course
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCourseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 180)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub format: CourseFormat,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "duration_hours")]
    pub duration_hours: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 180)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "certification_id")]
    pub certification_id: Option<Uuid>,
    pub status: CourseStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Course
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCourseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 180)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub format: Option<CourseFormat>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "duration_hours")]
    pub duration_hours: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cost: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 180)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "certification_id")]
    pub certification_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<CourseStatus>,
}

impl PatchCourseDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.description.is_some() || self.format.is_some() || self.duration_hours.is_some() || self.cost.is_some() || self.provider.is_some() || self.certification_id.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Course entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CourseResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub description: Option<String>,
    pub format: CourseFormat,
    pub duration_hours: Option<Decimal>,
    pub cost: Option<Decimal>,
    pub provider: Option<String>,
    pub certification_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub status: CourseStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Course entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CourseListResponseDto {
    /// List of items
    pub items: Vec<CourseResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CourseListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CourseResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CourseSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Course> for CourseResponseDto {
    fn from(entity: Course) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            name: entity.name,
            description: entity.description,
            format: entity.format,
            duration_hours: entity.duration_hours,
            cost: entity.cost,
            provider: entity.provider,
            certification_id: entity.certification_id,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<Course> for CourseSummaryDto {
    fn from(entity: Course) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            name: entity.name,
            description: entity.description,
            created_at,
        }
    }
}

impl From<CreateCourseDto> for Course {
    fn from(dto: CreateCourseDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            name: dto.name,
            description: dto.description,
            format: dto.format,
            duration_hours: dto.duration_hours,
            cost: dto.cost,
            provider: dto.provider,
            certification_id: dto.certification_id,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Course> for CourseResponseDto {
    fn from(entity: &Course) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            name: entity.name.clone(),
            description: entity.description.clone(),
            format: entity.format.clone(),
            duration_hours: entity.duration_hours.clone(),
            cost: entity.cost.clone(),
            provider: entity.provider.clone(),
            certification_id: entity.certification_id.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCourseDto> for Course {
    fn from_create_dto(dto: CreateCourseDto) -> backbone_core::ServiceResult<Self> {
        Ok(Course::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCourseDto> for Course {
    fn apply_update(mut self, dto: UpdateCourseDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.name = dto.name;
        self.description = dto.description;
        self.format = dto.format;
        self.duration_hours = dto.duration_hours;
        self.cost = dto.cost;
        self.provider = dto.provider;
        self.certification_id = dto.certification_id;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Course here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

