//! EmployeeSkill DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, NaiveDate, Utc};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AuditMetadata;
use crate::domain::entity::EmployeeSkill;
use crate::domain::entity::ProficiencyLevel;
use crate::domain::entity::SkillVerification;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new EmployeeSkill
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateEmployeeSkillDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "skill_id")]
    pub skill_id: Uuid,
    pub proficiency: ProficiencyLevel,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "years_experience"
    )]
    pub years_experience: Option<Decimal>,
    pub verification: SkillVerification,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "verified_by"
    )]
    pub verified_by: Option<Uuid>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "last_used_at"
    )]
    pub last_used_at: Option<NaiveDate>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a EmployeeSkill
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateEmployeeSkillDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "skill_id")]
    pub skill_id: Uuid,
    pub proficiency: ProficiencyLevel,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "years_experience"
    )]
    pub years_experience: Option<Decimal>,
    pub verification: SkillVerification,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "verified_by"
    )]
    pub verified_by: Option<Uuid>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "last_used_at"
    )]
    pub last_used_at: Option<NaiveDate>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a EmployeeSkill
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchEmployeeSkillDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "skill_id")]
    pub skill_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub proficiency: Option<ProficiencyLevel>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "years_experience")]
    pub years_experience: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verification: Option<SkillVerification>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "verified_by")]
    pub verified_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_used_at")]
    pub last_used_at: Option<NaiveDate>,
}

impl PatchEmployeeSkillDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.employee_id.is_some()
            || self.skill_id.is_some()
            || self.proficiency.is_some()
            || self.years_experience.is_some()
            || self.verification.is_some()
            || self.verified_by.is_some()
            || self.last_used_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for EmployeeSkill entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmployeeSkillResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub employee_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub skill_id: Uuid,
    pub proficiency: ProficiencyLevel,
    pub years_experience: Option<Decimal>,
    pub verification: SkillVerification,
    pub verified_by: Option<Uuid>,
    pub last_used_at: Option<NaiveDate>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for EmployeeSkill entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmployeeSkillListResponseDto {
    /// List of items
    pub items: Vec<EmployeeSkillResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl EmployeeSkillListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<EmployeeSkillResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EmployeeSkillSummaryDto {
    pub id: Uuid,
    pub employee_id: Uuid,
    pub skill_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<EmployeeSkill> for EmployeeSkillResponseDto {
    fn from(entity: EmployeeSkill) -> Self {
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            skill_id: entity.skill_id,
            proficiency: entity.proficiency,
            years_experience: entity.years_experience,
            verification: entity.verification,
            verified_by: entity.verified_by,
            last_used_at: entity.last_used_at,
            metadata: entity.metadata,
        }
    }
}

impl From<EmployeeSkill> for EmployeeSkillSummaryDto {
    fn from(entity: EmployeeSkill) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            skill_id: entity.skill_id,
            created_at,
        }
    }
}

impl From<CreateEmployeeSkillDto> for EmployeeSkill {
    fn from(dto: CreateEmployeeSkillDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            employee_id: dto.employee_id,
            skill_id: dto.skill_id,
            proficiency: dto.proficiency,
            years_experience: dto.years_experience,
            verification: dto.verification,
            verified_by: dto.verified_by,
            last_used_at: dto.last_used_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&EmployeeSkill> for EmployeeSkillResponseDto {
    fn from(entity: &EmployeeSkill) -> Self {
        Self {
            id: entity.id.clone(),
            employee_id: entity.employee_id.clone(),
            skill_id: entity.skill_id.clone(),
            proficiency: entity.proficiency.clone(),
            years_experience: entity.years_experience.clone(),
            verification: entity.verification.clone(),
            verified_by: entity.verified_by.clone(),
            last_used_at: entity.last_used_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateEmployeeSkillDto> for EmployeeSkill {
    fn from_create_dto(dto: CreateEmployeeSkillDto) -> backbone_core::ServiceResult<Self> {
        Ok(EmployeeSkill::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateEmployeeSkillDto> for EmployeeSkill {
    fn apply_update(mut self, dto: UpdateEmployeeSkillDto) -> backbone_core::ServiceResult<Self> {
        self.employee_id = dto.employee_id;
        self.skill_id = dto.skill_id;
        self.proficiency = dto.proficiency;
        self.years_experience = dto.years_experience;
        self.verification = dto.verification;
        self.verified_by = dto.verified_by;
        self.last_used_at = dto.last_used_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to EmployeeSkill here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
