//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod competency_specification;
pub mod course_specification;
pub mod course_enrollment_specification;
pub mod employee_competency_specification;
pub mod employee_skill_specification;
pub mod skill_specification;

// <<< CUSTOM
// END CUSTOM
