//! Domain policy for EmployeeSkill aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::EmployeeSkill;

/// Domain policy for EmployeeSkill — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<EmployeeSkill>` in the `// <<< CUSTOM` zone.
pub type EmployeeSkillDomainPolicy = PermitAllPolicy<EmployeeSkill>;

// <<< CUSTOM
// END CUSTOM
