//! Domain policy for EmployeeCompetency aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::EmployeeCompetency;

/// Domain policy for EmployeeCompetency — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<EmployeeCompetency>` in the `// <<< CUSTOM` zone.
pub type EmployeeCompetencyDomainPolicy = PermitAllPolicy<EmployeeCompetency>;

// <<< CUSTOM
// END CUSTOM
