//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod competency_domain_policy;
pub mod course_domain_policy;
pub mod course_enrollment_domain_policy;
pub mod employee_competency_domain_policy;
pub mod employee_skill_domain_policy;
pub mod skill_domain_policy;

pub use competency_domain_policy::CompetencyDomainPolicy;
pub use course_domain_policy::CourseDomainPolicy;
pub use course_enrollment_domain_policy::CourseEnrollmentDomainPolicy;
pub use employee_competency_domain_policy::EmployeeCompetencyDomainPolicy;
pub use employee_skill_domain_policy::EmployeeSkillDomainPolicy;
pub use skill_domain_policy::SkillDomainPolicy;

// <<< CUSTOM
// END CUSTOM
