//! Application service for Competency entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `competency_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCompetencyDto, UpdateCompetencyDto};
use crate::domain::entity::Competency;
use crate::infrastructure::persistence::CompetencyRepository;

/// Application service for Competency entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `competency_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CompetencyServiceCustom {
///     inner: Arc<CompetencyService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CompetencyService = GenericCrudService<
    Competency,
    CreateCompetencyDto,
    UpdateCompetencyDto,
    CompetencyRepository,
>;

// <<< CUSTOM
// END CUSTOM
