//! Application service for Course entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `course_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCourseDto, UpdateCourseDto};
use crate::domain::entity::Course;
use crate::infrastructure::persistence::CourseRepository;

/// Application service for Course entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `course_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CourseServiceCustom {
///     inner: Arc<CourseService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CourseService = GenericCrudService<
    Course,
    CreateCourseDto,
    UpdateCourseDto,
    CourseRepository,
>;

// <<< CUSTOM
// END CUSTOM
