//! Application service for EmployeeCompetency entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `employee_competency_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateEmployeeCompetencyDto, UpdateEmployeeCompetencyDto};
use crate::domain::entity::EmployeeCompetency;
use crate::infrastructure::persistence::EmployeeCompetencyRepository;

/// Application service for EmployeeCompetency entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `employee_competency_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct EmployeeCompetencyServiceCustom {
///     inner: Arc<EmployeeCompetencyService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type EmployeeCompetencyService = GenericCrudService<
    EmployeeCompetency,
    CreateEmployeeCompetencyDto,
    UpdateEmployeeCompetencyDto,
    EmployeeCompetencyRepository,
>;

// <<< CUSTOM
// END CUSTOM
