//! Application service for EmployeeSkill entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `employee_skill_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateEmployeeSkillDto, UpdateEmployeeSkillDto};
use crate::domain::entity::EmployeeSkill;
use crate::infrastructure::persistence::EmployeeSkillRepository;

/// Application service for EmployeeSkill entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `employee_skill_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct EmployeeSkillServiceCustom {
///     inner: Arc<EmployeeSkillService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type EmployeeSkillService = GenericCrudService<
    EmployeeSkill,
    CreateEmployeeSkillDto,
    UpdateEmployeeSkillDto,
    EmployeeSkillRepository,
>;

// <<< CUSTOM
// END CUSTOM
