//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod competency_service;
pub mod course_service;
pub mod course_enrollment_service;
pub mod employee_competency_service;
pub mod employee_skill_service;
pub mod skill_service;

// <<< CUSTOM
// END CUSTOM

pub use competency_service::CompetencyService;
pub use course_service::CourseService;
pub use course_enrollment_service::CourseEnrollmentService;
pub use employee_competency_service::EmployeeCompetencyService;
pub use employee_skill_service::EmployeeSkillService;
pub use skill_service::SkillService;
// <<< CUSTOM
// END CUSTOM
