//! Application service for Skill entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `skill_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateSkillDto, UpdateSkillDto};
use crate::domain::entity::Skill;
use crate::infrastructure::persistence::SkillRepository;

/// Application service for Skill entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `skill_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct SkillServiceCustom {
///     inner: Arc<SkillService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type SkillService = GenericCrudService<
    Skill,
    CreateSkillDto,
    UpdateSkillDto,
    SkillRepository,
>;

// <<< CUSTOM
// END CUSTOM
