-- CourseEnrollment Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the learning.course_enrollments table.
-- Customize this file to add your initial data.

-- INSERT INTO learning.course_enrollments (
--     id,
--     company_id,
--     course_id,
--     employee_id,
--     status,
--     enrolled_at,
--     completed_at,
--     score,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO learning.course_enrollments (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

