-- EmployeeSkill Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the learning.employee_skills table.
-- Customize this file to add your initial data.

-- INSERT INTO learning.employee_skills (
--     id,
--     employee_id,
--     skill_id,
--     proficiency,
--     years_experience,
--     verification,
--     verified_by,
--     last_used_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO learning.employee_skills (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

