-- EmployeeCompetency Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the learning.employee_competencies table.
-- Customize this file to add your initial data.

-- INSERT INTO learning.employee_competencies (
--     id,
--     company_id,
--     employee_id,
--     competency_id,
--     level,
--     assessed_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO learning.employee_competencies (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

