-- Migration: Create course_enrollments table
-- Generated by metaphor-schema

-- Create enrollment_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enrollment_status') THEN
        CREATE TYPE enrollment_status AS ENUM ('enrolled', 'in_progress', 'completed', 'withdrawn', 'failed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS learning;

CREATE TABLE IF NOT EXISTS learning.course_enrollments (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    course_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    status enrollment_status NOT NULL DEFAULT 'enrolled',
    enrolled_at DATE NOT NULL,
    completed_at DATE,
    score NUMERIC(5, 2) CHECK (score >= 0),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_course_enrollments_company_id_employee_id ON learning.course_enrollments (company_id, employee_id);

CREATE INDEX IF NOT EXISTS idx_course_enrollments_course_id ON learning.course_enrollments (course_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_course_enrollments_metadata_gin ON learning.course_enrollments USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_course_enrollments_metadata_deleted_at ON learning.course_enrollments ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_course_enrollments_metadata_created_at ON learning.course_enrollments ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_course_enrollments_metadata_updated_at ON learning.course_enrollments ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION learning.course_enrollments_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS course_enrollments_insert_audit ON learning.course_enrollments;
CREATE TRIGGER course_enrollments_insert_audit BEFORE INSERT ON learning.course_enrollments
    FOR EACH ROW EXECUTE FUNCTION learning.course_enrollments_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS course_enrollments_update_audit ON learning.course_enrollments;
CREATE TRIGGER course_enrollments_update_audit BEFORE UPDATE ON learning.course_enrollments
    FOR EACH ROW EXECUTE FUNCTION learning.course_enrollments_audit_timestamp();
