-- Audit Triggers Migration for learning module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Competency (learning.competencies)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION learning.competencies_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS competencies_insert_audit ON learning.competencies;
CREATE TRIGGER competencies_insert_audit BEFORE INSERT ON learning.competencies
    FOR EACH ROW EXECUTE FUNCTION learning.competencies_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS competencies_update_audit ON learning.competencies;
CREATE TRIGGER competencies_update_audit BEFORE UPDATE ON learning.competencies
    FOR EACH ROW EXECUTE FUNCTION learning.competencies_audit_timestamp();

-- ==============================================================================
-- Table: Course (learning.courses)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION learning.courses_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS courses_insert_audit ON learning.courses;
CREATE TRIGGER courses_insert_audit BEFORE INSERT ON learning.courses
    FOR EACH ROW EXECUTE FUNCTION learning.courses_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS courses_update_audit ON learning.courses;
CREATE TRIGGER courses_update_audit BEFORE UPDATE ON learning.courses
    FOR EACH ROW EXECUTE FUNCTION learning.courses_audit_timestamp();

-- ==============================================================================
-- Table: CourseEnrollment (learning.course_enrollments)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION learning.course_enrollments_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS course_enrollments_insert_audit ON learning.course_enrollments;
CREATE TRIGGER course_enrollments_insert_audit BEFORE INSERT ON learning.course_enrollments
    FOR EACH ROW EXECUTE FUNCTION learning.course_enrollments_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS course_enrollments_update_audit ON learning.course_enrollments;
CREATE TRIGGER course_enrollments_update_audit BEFORE UPDATE ON learning.course_enrollments
    FOR EACH ROW EXECUTE FUNCTION learning.course_enrollments_audit_timestamp();

-- ==============================================================================
-- Table: EmployeeCompetency (learning.employee_competencies)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION learning.employee_competencies_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS employee_competencies_insert_audit ON learning.employee_competencies;
CREATE TRIGGER employee_competencies_insert_audit BEFORE INSERT ON learning.employee_competencies
    FOR EACH ROW EXECUTE FUNCTION learning.employee_competencies_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS employee_competencies_update_audit ON learning.employee_competencies;
CREATE TRIGGER employee_competencies_update_audit BEFORE UPDATE ON learning.employee_competencies
    FOR EACH ROW EXECUTE FUNCTION learning.employee_competencies_audit_timestamp();

-- ==============================================================================
-- Table: EmployeeSkill (learning.employee_skills)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION learning.employee_skills_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS employee_skills_insert_audit ON learning.employee_skills;
CREATE TRIGGER employee_skills_insert_audit BEFORE INSERT ON learning.employee_skills
    FOR EACH ROW EXECUTE FUNCTION learning.employee_skills_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS employee_skills_update_audit ON learning.employee_skills;
CREATE TRIGGER employee_skills_update_audit BEFORE UPDATE ON learning.employee_skills
    FOR EACH ROW EXECUTE FUNCTION learning.employee_skills_audit_timestamp();

-- ==============================================================================
-- Table: Skill (learning.skills)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION learning.skills_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS skills_insert_audit ON learning.skills;
CREATE TRIGGER skills_insert_audit BEFORE INSERT ON learning.skills
    FOR EACH ROW EXECUTE FUNCTION learning.skills_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS skills_update_audit ON learning.skills;
CREATE TRIGGER skills_update_audit BEFORE UPDATE ON learning.skills
    FOR EACH ROW EXECUTE FUNCTION learning.skills_audit_timestamp();

