-- Enum types for learning module
-- Generated by metaphor-schema

-- Create competency_category enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'competency_category') THEN
        CREATE TYPE competency_category AS ENUM ('technical', 'leadership', 'soft_skill', 'safety', 'compliance');
    END IF;
END
$$;

-- Create course_format enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'course_format') THEN
        CREATE TYPE course_format AS ENUM ('online', 'onsite', 'blended', 'self_paced');
    END IF;
END
$$;

-- Create enrollment_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enrollment_status') THEN
        CREATE TYPE enrollment_status AS ENUM ('enrolled', 'in_progress', 'completed', 'withdrawn', 'failed');
    END IF;
END
$$;

-- Create proficiency_level enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'proficiency_level') THEN
        CREATE TYPE proficiency_level AS ENUM ('novice', 'beginner', 'intermediate', 'advanced', 'expert');
    END IF;
END
$$;

-- Create skill_verification enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'skill_verification') THEN
        CREATE TYPE skill_verification AS ENUM ('self_reported', 'assessed', 'certified');
    END IF;
END
$$;

-- Create skill_category enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'skill_category') THEN
        CREATE TYPE skill_category AS ENUM ('technical', 'soft', 'tool', 'language', 'domain', 'certification');
    END IF;
END
$$;

