-- Migration: Create courses table
-- Generated by metaphor-schema

-- Create course_format enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'course_format') THEN
        CREATE TYPE course_format AS ENUM ('online', 'onsite', 'blended', 'self_paced');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS learning;

CREATE TABLE IF NOT EXISTS learning.courses (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    format course_format NOT NULL DEFAULT 'online',
    duration_hours NUMERIC(6, 2) CHECK (duration_hours >= 0),
    cost NUMERIC(18, 2) CHECK (cost >= 0),
    provider TEXT,
    certification_id UUID,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_courses_company_id_name ON learning.courses (company_id, name) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_courses_metadata_gin ON learning.courses USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_courses_metadata_deleted_at ON learning.courses ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_courses_metadata_created_at ON learning.courses ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_courses_metadata_updated_at ON learning.courses ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION learning.courses_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS courses_insert_audit ON learning.courses;
CREATE TRIGGER courses_insert_audit BEFORE INSERT ON learning.courses
    FOR EACH ROW EXECUTE FUNCTION learning.courses_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS courses_update_audit ON learning.courses;
CREATE TRIGGER courses_update_audit BEFORE UPDATE ON learning.courses
    FOR EACH ROW EXECUTE FUNCTION learning.courses_audit_timestamp();
