-- Migration: Create employee_competencies table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS learning;

CREATE TABLE IF NOT EXISTS learning.employee_competencies (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    competency_id UUID NOT NULL,
    level INTEGER NOT NULL DEFAULT 3,
    assessed_at DATE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_employee_competencies_company_id_employee_id ON learning.employee_competencies (company_id, employee_id);

CREATE INDEX IF NOT EXISTS idx_employee_competencies_competency_id ON learning.employee_competencies (competency_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_employee_competencies_metadata_gin ON learning.employee_competencies USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_employee_competencies_metadata_deleted_at ON learning.employee_competencies ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_employee_competencies_metadata_created_at ON learning.employee_competencies ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_employee_competencies_metadata_updated_at ON learning.employee_competencies ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION learning.employee_competencies_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS employee_competencies_insert_audit ON learning.employee_competencies;
CREATE TRIGGER employee_competencies_insert_audit BEFORE INSERT ON learning.employee_competencies
    FOR EACH ROW EXECUTE FUNCTION learning.employee_competencies_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS employee_competencies_update_audit ON learning.employee_competencies;
CREATE TRIGGER employee_competencies_update_audit BEFORE UPDATE ON learning.employee_competencies
    FOR EACH ROW EXECUTE FUNCTION learning.employee_competencies_audit_timestamp();
