-- Migration: Create competencies table
-- Generated by metaphor-schema

-- Create competency_category enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'competency_category') THEN
        CREATE TYPE competency_category AS ENUM ('technical', 'leadership', 'soft_skill', 'safety', 'compliance');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS learning;

CREATE TABLE IF NOT EXISTS learning.competencies (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    category competency_category,
    description TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_competencies_company_id_name ON learning.competencies (company_id, name) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_competencies_metadata_gin ON learning.competencies USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_competencies_metadata_deleted_at ON learning.competencies ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_competencies_metadata_created_at ON learning.competencies ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_competencies_metadata_updated_at ON learning.competencies ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION learning.competencies_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS competencies_insert_audit ON learning.competencies;
CREATE TRIGGER competencies_insert_audit BEFORE INSERT ON learning.competencies
    FOR EACH ROW EXECUTE FUNCTION learning.competencies_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS competencies_update_audit ON learning.competencies;
CREATE TRIGGER competencies_update_audit BEFORE UPDATE ON learning.competencies
    FOR EACH ROW EXECUTE FUNCTION learning.competencies_audit_timestamp();
