-- Migration: Create employee_skills table
-- Generated by metaphor-schema

-- Create proficiency_level enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'proficiency_level') THEN
        CREATE TYPE proficiency_level AS ENUM ('novice', 'beginner', 'intermediate', 'advanced', 'expert');
    END IF;
END
$$;

-- Create skill_verification enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'skill_verification') THEN
        CREATE TYPE skill_verification AS ENUM ('self_reported', 'assessed', 'certified');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS learning;

CREATE TABLE IF NOT EXISTS learning.employee_skills (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    skill_id UUID NOT NULL,
    proficiency proficiency_level NOT NULL DEFAULT 'intermediate',
    years_experience NUMERIC(5, 1) CHECK (years_experience >= 0),
    verification skill_verification NOT NULL DEFAULT 'self_reported',
    verified_by UUID,
    last_used_at DATE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_employee_skills_employee_id ON learning.employee_skills (employee_id);

CREATE INDEX IF NOT EXISTS idx_employee_skills_skill_id ON learning.employee_skills (skill_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_employee_skills_metadata_gin ON learning.employee_skills USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_employee_skills_metadata_deleted_at ON learning.employee_skills ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_employee_skills_metadata_created_at ON learning.employee_skills ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_employee_skills_metadata_updated_at ON learning.employee_skills ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION learning.employee_skills_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS employee_skills_insert_audit ON learning.employee_skills;
CREATE TRIGGER employee_skills_insert_audit BEFORE INSERT ON learning.employee_skills
    FOR EACH ROW EXECUTE FUNCTION learning.employee_skills_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS employee_skills_update_audit ON learning.employee_skills;
CREATE TRIGGER employee_skills_update_audit BEFORE UPDATE ON learning.employee_skills
    FOR EACH ROW EXECUTE FUNCTION learning.employee_skills_audit_timestamp();
