-- Company RLS fence for learning module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for learning.competencies
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE learning.competencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning.competencies FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS competencies_company_isolation ON learning.competencies;
CREATE POLICY competencies_company_isolation ON learning.competencies
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for learning.courses
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE learning.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning.courses FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS courses_company_isolation ON learning.courses;
CREATE POLICY courses_company_isolation ON learning.courses
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for learning.course_enrollments
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE learning.course_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning.course_enrollments FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS course_enrollments_company_isolation ON learning.course_enrollments;
CREATE POLICY course_enrollments_company_isolation ON learning.course_enrollments
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for learning.employee_competencies
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE learning.employee_competencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning.employee_competencies FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS employee_competencies_company_isolation ON learning.employee_competencies;
CREATE POLICY employee_competencies_company_isolation ON learning.employee_competencies
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for learning.employee_skills
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE learning.employee_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning.employee_skills FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS employee_skills_company_isolation ON learning.employee_skills;
CREATE POLICY employee_skills_company_isolation ON learning.employee_skills
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for learning.skills
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE learning.skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning.skills FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS skills_company_isolation ON learning.skills;
CREATE POLICY skills_company_isolation ON learning.skills
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

