//! Event handler trait for Competency events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CompetencyEvent;

/// Event handler for Competency events.
/// Implement this trait to react to Competency lifecycle events.
pub trait CompetencyEventHandler: EventHandler<CompetencyEvent> {}
