//! Domain events for Competency entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Competency;

/// Domain events for Competency — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Competency>)` variant.
pub type CompetencyEvent = CrudEvent<Competency>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Competency events.
pub type CompetencyEventPublisher = Arc<dyn CrudEventPublisher<Competency> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCompetencyEventPublisher = NoOpCrudEventPublisher<Competency>;
