//! Event handler trait for CourseEnrollment events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CourseEnrollmentEvent;

/// Event handler for CourseEnrollment events.
/// Implement this trait to react to CourseEnrollment lifecycle events.
pub trait CourseEnrollmentEventHandler: EventHandler<CourseEnrollmentEvent> {}
