//! Domain events for CourseEnrollment entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::CourseEnrollment;

/// Domain events for CourseEnrollment — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<CourseEnrollment>)` variant.
pub type CourseEnrollmentEvent = CrudEvent<CourseEnrollment>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for CourseEnrollment events.
pub type CourseEnrollmentEventPublisher = Arc<dyn CrudEventPublisher<CourseEnrollment> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCourseEnrollmentEventPublisher = NoOpCrudEventPublisher<CourseEnrollment>;
