//! Domain events for Course entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Course;

/// Domain events for Course — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Course>)` variant.
pub type CourseEvent = CrudEvent<Course>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Course events.
pub type CourseEventPublisher = Arc<dyn CrudEventPublisher<Course> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCourseEventPublisher = NoOpCrudEventPublisher<Course>;
