//! Event handler trait for Course events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CourseEvent;

/// Event handler for Course events.
/// Implement this trait to react to Course lifecycle events.
pub trait CourseEventHandler: EventHandler<CourseEvent> {}
