//! Event handler trait for EmployeeSkill events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EmployeeSkillEvent;

/// Event handler for EmployeeSkill events.
/// Implement this trait to react to EmployeeSkill lifecycle events.
pub trait EmployeeSkillEventHandler: EventHandler<EmployeeSkillEvent> {}
