//! Domain events for EmployeeSkill entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::EmployeeSkill;

/// Domain events for EmployeeSkill — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<EmployeeSkill>)` variant.
pub type EmployeeSkillEvent = CrudEvent<EmployeeSkill>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for EmployeeSkill events.
pub type EmployeeSkillEventPublisher = Arc<dyn CrudEventPublisher<EmployeeSkill> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopEmployeeSkillEventPublisher = NoOpCrudEventPublisher<EmployeeSkill>;
