//! Event handler trait for EmployeeCompetency events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EmployeeCompetencyEvent;

/// Event handler for EmployeeCompetency events.
/// Implement this trait to react to EmployeeCompetency lifecycle events.
pub trait EmployeeCompetencyEventHandler: EventHandler<EmployeeCompetencyEvent> {}
