//! Domain events for EmployeeCompetency entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::EmployeeCompetency;

/// Domain events for EmployeeCompetency — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<EmployeeCompetency>)` variant.
pub type EmployeeCompetencyEvent = CrudEvent<EmployeeCompetency>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for EmployeeCompetency events.
pub type EmployeeCompetencyEventPublisher = Arc<dyn CrudEventPublisher<EmployeeCompetency> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopEmployeeCompetencyEventPublisher = NoOpCrudEventPublisher<EmployeeCompetency>;
