//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod competency_events;
pub mod competency_event_handlers;
pub mod course_events;
pub mod course_event_handlers;
pub mod course_enrollment_events;
pub mod course_enrollment_event_handlers;
pub mod employee_competency_events;
pub mod employee_competency_event_handlers;
pub mod employee_skill_events;
pub mod employee_skill_event_handlers;
pub mod skill_events;
pub mod skill_event_handlers;

pub use competency_events::{CompetencyEvent, CompetencyEventPublisher, NoopCompetencyEventPublisher};
pub use competency_event_handlers::CompetencyEventHandler;
pub use course_events::{CourseEvent, CourseEventPublisher, NoopCourseEventPublisher};
pub use course_event_handlers::CourseEventHandler;
pub use course_enrollment_events::{CourseEnrollmentEvent, CourseEnrollmentEventPublisher, NoopCourseEnrollmentEventPublisher};
pub use course_enrollment_event_handlers::CourseEnrollmentEventHandler;
pub use employee_competency_events::{EmployeeCompetencyEvent, EmployeeCompetencyEventPublisher, NoopEmployeeCompetencyEventPublisher};
pub use employee_competency_event_handlers::EmployeeCompetencyEventHandler;
pub use employee_skill_events::{EmployeeSkillEvent, EmployeeSkillEventPublisher, NoopEmployeeSkillEventPublisher};
pub use employee_skill_event_handlers::EmployeeSkillEventHandler;
pub use skill_events::{SkillEvent, SkillEventPublisher, NoopSkillEventPublisher};
pub use skill_event_handlers::SkillEventHandler;

// <<< CUSTOM
// END CUSTOM
