//! Event handler trait for Skill events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SkillEvent;

/// Event handler for Skill events.
/// Implement this trait to react to Skill lifecycle events.
pub trait SkillEventHandler: EventHandler<SkillEvent> {}
