//! Domain events for Skill entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Skill;

/// Domain events for Skill — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Skill>)` variant.
pub type SkillEvent = CrudEvent<Skill>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Skill events.
pub type SkillEventPublisher = Arc<dyn CrudEventPublisher<Skill> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSkillEventPublisher = NoOpCrudEventPublisher<Skill>;
