//! Competency seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Competency data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// COMPETENCY SEEDER
// ============================================================================

/// Seeder for competency
pub struct SeedCompetencySeeder;

impl SeedCompetencySeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedCompetencySeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedCompetencySeeder {
    fn name(&self) -> &'static str {
        "SeedCompetencySeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if learning.competencies table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM learning.competencies")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/competency_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM learning.competencies")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

