//! Skill seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Skill data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SKILL SEEDER
// ============================================================================

/// Seeder for skill
pub struct SeedSkillSeeder;

impl SeedSkillSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedSkillSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedSkillSeeder {
    fn name(&self) -> &'static str {
        "SeedSkillSeeder"
    }

    fn order(&self) -> i32 {
        6
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if learning.skills table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM learning.skills")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/skill_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM learning.skills")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

