//! Repository trait for Course aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Course aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::{Course, CourseFormat, CourseStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CoursePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CoursePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CoursePaginatedResult {
    pub data: Vec<Course>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CourseFilter {
    pub name: Option<String>,
    pub description: Option<String>,
    pub format: Option<CourseFormat>,
    pub provider: Option<String>,
    pub certification_id: Option<Uuid>,
    pub status: Option<CourseStatus>,
}

impl CourseFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some()
            || self.description.is_some()
            || self.format.is_some()
            || self.provider.is_some()
            || self.certification_id.is_some()
            || self.status.is_some()
    }
}

/// Repository trait for Course aggregate
///
/// This trait defines the persistence contract for Course entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CourseRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new course entity
    async fn save(&self, entity: &Course) -> Result<Course>;

    /// Find course by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Course>>;

    /// Find all course entities
    async fn find_all(&self) -> Result<Vec<Course>>;

    /// Update course by ID
    async fn update(&self, id: &str, entity: &Course) -> Result<Option<Course>>;

    /// Delete course by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List course with pagination
    async fn list(&self, params: CoursePaginationParams) -> Result<CoursePaginatedResult>;

    /// List course with pagination and filters
    async fn list_with_filters(
        &self,
        params: CoursePaginationParams,
        filters: CourseFilter,
    ) -> Result<CoursePaginatedResult>;

    /// Count all course entities
    async fn count(&self) -> Result<u64>;

    /// Count course entities matching filters
    async fn count_with_filters(&self, filters: CourseFilter) -> Result<u64>;

    /// Check if course exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete course by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted course by ID
    async fn restore(&self, id: &str) -> Result<Option<Course>>;

    /// List soft-deleted course entities
    async fn list_deleted(&self, params: CoursePaginationParams) -> Result<CoursePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save course entities
    async fn bulk_save(&self, entities: &[Course]) -> Result<Vec<Course>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
