//! Repository trait for CourseEnrollment aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the CourseEnrollment aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::{CourseEnrollment, EnrollmentStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CourseEnrollmentPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CourseEnrollmentPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CourseEnrollmentPaginatedResult {
    pub data: Vec<CourseEnrollment>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CourseEnrollmentFilter {
    pub course_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub status: Option<EnrollmentStatus>,
}

impl CourseEnrollmentFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.course_id.is_some() || self.employee_id.is_some() || self.status.is_some()
    }
}

/// Repository trait for CourseEnrollment aggregate
///
/// This trait defines the persistence contract for CourseEnrollment entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CourseEnrollmentRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new course_enrollment entity
    async fn save(&self, entity: &CourseEnrollment) -> Result<CourseEnrollment>;

    /// Find course_enrollment by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<CourseEnrollment>>;

    /// Find all course_enrollment entities
    async fn find_all(&self) -> Result<Vec<CourseEnrollment>>;

    /// Update course_enrollment by ID
    async fn update(&self, id: &str, entity: &CourseEnrollment)
        -> Result<Option<CourseEnrollment>>;

    /// Delete course_enrollment by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List course_enrollment with pagination
    async fn list(
        &self,
        params: CourseEnrollmentPaginationParams,
    ) -> Result<CourseEnrollmentPaginatedResult>;

    /// List course_enrollment with pagination and filters
    async fn list_with_filters(
        &self,
        params: CourseEnrollmentPaginationParams,
        filters: CourseEnrollmentFilter,
    ) -> Result<CourseEnrollmentPaginatedResult>;

    /// Count all course_enrollment entities
    async fn count(&self) -> Result<u64>;

    /// Count course_enrollment entities matching filters
    async fn count_with_filters(&self, filters: CourseEnrollmentFilter) -> Result<u64>;

    /// Check if course_enrollment exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete course_enrollment by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted course_enrollment by ID
    async fn restore(&self, id: &str) -> Result<Option<CourseEnrollment>>;

    /// List soft-deleted course_enrollment entities
    async fn list_deleted(
        &self,
        params: CourseEnrollmentPaginationParams,
    ) -> Result<CourseEnrollmentPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save course_enrollment entities
    async fn bulk_save(&self, entities: &[CourseEnrollment]) -> Result<Vec<CourseEnrollment>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
