//! Repository trait for EmployeeSkill aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the EmployeeSkill aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{EmployeeSkill, ProficiencyLevel, SkillVerification};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmployeeSkillPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl EmployeeSkillPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct EmployeeSkillPaginatedResult {
    pub data: Vec<EmployeeSkill>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmployeeSkillFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub skill_id: Option<Uuid>,
    pub proficiency: Option<ProficiencyLevel>,
    pub verification: Option<SkillVerification>,
    pub verified_by: Option<Uuid>,
}

impl EmployeeSkillFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.skill_id.is_some() || self.proficiency.is_some() || self.verification.is_some() || self.verified_by.is_some()
    }
}

/// Repository trait for EmployeeSkill aggregate
///
/// This trait defines the persistence contract for EmployeeSkill entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait EmployeeSkillRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new employee_skill entity
    async fn save(&self, entity: &EmployeeSkill) -> Result<EmployeeSkill>;

    /// Find employee_skill by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<EmployeeSkill>>;

    /// Find all employee_skill entities
    async fn find_all(&self) -> Result<Vec<EmployeeSkill>>;

    /// Update employee_skill by ID
    async fn update(&self, id: &str, entity: &EmployeeSkill) -> Result<Option<EmployeeSkill>>;

    /// Delete employee_skill by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List employee_skill with pagination
    async fn list(&self, params: EmployeeSkillPaginationParams) -> Result<EmployeeSkillPaginatedResult>;

    /// List employee_skill with pagination and filters
    async fn list_with_filters(&self, params: EmployeeSkillPaginationParams, filters: EmployeeSkillFilter) -> Result<EmployeeSkillPaginatedResult>;

    /// Count all employee_skill entities
    async fn count(&self) -> Result<u64>;

    /// Count employee_skill entities matching filters
    async fn count_with_filters(&self, filters: EmployeeSkillFilter) -> Result<u64>;

    /// Check if employee_skill exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete employee_skill by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted employee_skill by ID
    async fn restore(&self, id: &str) -> Result<Option<EmployeeSkill>>;

    /// List soft-deleted employee_skill entities
    async fn list_deleted(&self, params: EmployeeSkillPaginationParams) -> Result<EmployeeSkillPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save employee_skill entities
    async fn bulk_save(&self, entities: &[EmployeeSkill]) -> Result<Vec<EmployeeSkill>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
