//! Repository trait for EmployeeCompetency aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the EmployeeCompetency aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::EmployeeCompetency;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmployeeCompetencyPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl EmployeeCompetencyPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct EmployeeCompetencyPaginatedResult {
    pub data: Vec<EmployeeCompetency>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmployeeCompetencyFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub competency_id: Option<Uuid>,
}

impl EmployeeCompetencyFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.competency_id.is_some()
    }
}

/// Repository trait for EmployeeCompetency aggregate
///
/// This trait defines the persistence contract for EmployeeCompetency entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait EmployeeCompetencyRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new employee_competency entity
    async fn save(&self, entity: &EmployeeCompetency) -> Result<EmployeeCompetency>;

    /// Find employee_competency by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<EmployeeCompetency>>;

    /// Find all employee_competency entities
    async fn find_all(&self) -> Result<Vec<EmployeeCompetency>>;

    /// Update employee_competency by ID
    async fn update(&self, id: &str, entity: &EmployeeCompetency) -> Result<Option<EmployeeCompetency>>;

    /// Delete employee_competency by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List employee_competency with pagination
    async fn list(&self, params: EmployeeCompetencyPaginationParams) -> Result<EmployeeCompetencyPaginatedResult>;

    /// List employee_competency with pagination and filters
    async fn list_with_filters(&self, params: EmployeeCompetencyPaginationParams, filters: EmployeeCompetencyFilter) -> Result<EmployeeCompetencyPaginatedResult>;

    /// Count all employee_competency entities
    async fn count(&self) -> Result<u64>;

    /// Count employee_competency entities matching filters
    async fn count_with_filters(&self, filters: EmployeeCompetencyFilter) -> Result<u64>;

    /// Check if employee_competency exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete employee_competency by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted employee_competency by ID
    async fn restore(&self, id: &str) -> Result<Option<EmployeeCompetency>>;

    /// List soft-deleted employee_competency entities
    async fn list_deleted(&self, params: EmployeeCompetencyPaginationParams) -> Result<EmployeeCompetencyPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save employee_competency entities
    async fn bulk_save(&self, entities: &[EmployeeCompetency]) -> Result<Vec<EmployeeCompetency>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
