//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod competency_repository;
pub mod course_repository;
pub mod course_enrollment_repository;
pub mod employee_competency_repository;
pub mod employee_skill_repository;
pub mod skill_repository;

// Re-exports
pub use competency_repository::{
    CompetencyRepository,
    CompetencyPaginationParams,
    CompetencyPaginatedResult,
    CompetencyFilter,
};
pub use course_repository::{
    CourseRepository,
    CoursePaginationParams,
    CoursePaginatedResult,
    CourseFilter,
};
pub use course_enrollment_repository::{
    CourseEnrollmentRepository,
    CourseEnrollmentPaginationParams,
    CourseEnrollmentPaginatedResult,
    CourseEnrollmentFilter,
};
pub use employee_competency_repository::{
    EmployeeCompetencyRepository,
    EmployeeCompetencyPaginationParams,
    EmployeeCompetencyPaginatedResult,
    EmployeeCompetencyFilter,
};
pub use employee_skill_repository::{
    EmployeeSkillRepository,
    EmployeeSkillPaginationParams,
    EmployeeSkillPaginatedResult,
    EmployeeSkillFilter,
};
pub use skill_repository::{
    SkillRepository,
    SkillPaginationParams,
    SkillPaginatedResult,
    SkillFilter,
};
