//! Repository trait for Skill aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Skill aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Skill, SkillCategory};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SkillPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SkillPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SkillPaginatedResult {
    pub data: Vec<Skill>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SkillFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub category: Option<SkillCategory>,
    pub description: Option<String>,
}

impl SkillFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.category.is_some() || self.description.is_some()
    }
}

/// Repository trait for Skill aggregate
///
/// This trait defines the persistence contract for Skill entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SkillRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new skill entity
    async fn save(&self, entity: &Skill) -> Result<Skill>;

    /// Find skill by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Skill>>;

    /// Find all skill entities
    async fn find_all(&self) -> Result<Vec<Skill>>;

    /// Update skill by ID
    async fn update(&self, id: &str, entity: &Skill) -> Result<Option<Skill>>;

    /// Delete skill by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List skill with pagination
    async fn list(&self, params: SkillPaginationParams) -> Result<SkillPaginatedResult>;

    /// List skill with pagination and filters
    async fn list_with_filters(&self, params: SkillPaginationParams, filters: SkillFilter) -> Result<SkillPaginatedResult>;

    /// Count all skill entities
    async fn count(&self) -> Result<u64>;

    /// Count skill entities matching filters
    async fn count_with_filters(&self, filters: SkillFilter) -> Result<u64>;

    /// Check if skill exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete skill by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted skill by ID
    async fn restore(&self, id: &str) -> Result<Option<Skill>>;

    /// List soft-deleted skill entities
    async fn list_deleted(&self, params: SkillPaginationParams) -> Result<SkillPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save skill entities
    async fn bulk_save(&self, entities: &[Skill]) -> Result<Vec<Skill>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
