//! Repository for Competency entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Competency, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Competency;

/// Table name for Competency entities
pub const TABLE_NAME: &str = "learning.competencies";

/// Repository for Competency entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CompetencyRepository(
    backbone_orm::GenericCrudRepository<Competency, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CompetencyRepository {
    type Target = backbone_orm::GenericCrudRepository<Competency, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CompetencyRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(CompetencyRepository, Competency, soft_delete);
