//! Repository for EmployeeSkill entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<EmployeeSkill, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::EmployeeSkill;

/// Table name for EmployeeSkill entities
pub const TABLE_NAME: &str = "learning.employee_skills";

/// Repository for EmployeeSkill entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct EmployeeSkillRepository(
    backbone_orm::GenericCrudRepository<EmployeeSkill, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for EmployeeSkillRepository {
    type Target = backbone_orm::GenericCrudRepository<EmployeeSkill, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl EmployeeSkillRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(EmployeeSkillRepository, EmployeeSkill, soft_delete);
