//! Repository for EmployeeCompetency entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<EmployeeCompetency, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::EmployeeCompetency;

/// Table name for EmployeeCompetency entities
pub const TABLE_NAME: &str = "learning.employee_competencies";

/// Repository for EmployeeCompetency entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct EmployeeCompetencyRepository(
    backbone_orm::GenericCrudRepository<EmployeeCompetency, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for EmployeeCompetencyRepository {
    type Target = backbone_orm::GenericCrudRepository<EmployeeCompetency, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl EmployeeCompetencyRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(EmployeeCompetencyRepository, EmployeeCompetency, soft_delete);
