//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod competency_repository;
mod course_repository;
mod course_enrollment_repository;
mod employee_competency_repository;
mod employee_skill_repository;
mod skill_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use competency_repository::CompetencyRepository;
pub use course_repository::CourseRepository;
pub use course_enrollment_repository::CourseEnrollmentRepository;
pub use employee_competency_repository::EmployeeCompetencyRepository;
pub use employee_skill_repository::EmployeeSkillRepository;
pub use skill_repository::SkillRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
