//! Repository for Skill entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Skill, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Skill;

/// Table name for Skill entities
pub const TABLE_NAME: &str = "learning.skills";

/// Repository for Skill entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SkillRepository(
    backbone_orm::GenericCrudRepository<Skill, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SkillRepository {
    type Target = backbone_orm::GenericCrudRepository<Skill, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SkillRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SkillRepository, Skill, soft_delete);
