//! Validator for Competency entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Competency>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Competency;

/// Validator type alias for Competency entities.
pub type CompetencyValidator = EntityValidator<Competency>;

/// Build a validator for Competency with all schema-defined field rules.
pub fn competency_validator() -> CompetencyValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Competency| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &Competency| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
