//! Validator for CourseEnrollment entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CourseEnrollment>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::CourseEnrollment;

/// Validator type alias for CourseEnrollment entities.
pub type CourseEnrollmentValidator = EntityValidator<CourseEnrollment>;

/// Build a validator for CourseEnrollment with all schema-defined field rules.
pub fn course_enrollment_validator() -> CourseEnrollmentValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
