//! Validator for Course entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Course>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::Course;

/// Validator type alias for Course entities.
pub type CourseValidator = EntityValidator<Course>;

/// Build a validator for Course with all schema-defined field rules.
pub fn course_validator() -> CourseValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Course| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &Course| e.description.as_deref()))
        .rule(OptionalNotBlank::new("provider", |e: &Course| e.provider.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
