//! Validator for EmployeeSkill entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<EmployeeSkill>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::EmployeeSkill;

/// Validator type alias for EmployeeSkill entities.
pub type EmployeeSkillValidator = EntityValidator<EmployeeSkill>;

/// Build a validator for EmployeeSkill with all schema-defined field rules.
pub fn employee_skill_validator() -> EmployeeSkillValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
