//! Validator for EmployeeCompetency entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<EmployeeCompetency>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::EmployeeCompetency;

/// Validator type alias for EmployeeCompetency entities.
pub type EmployeeCompetencyValidator = EntityValidator<EmployeeCompetency>;

/// Build a validator for EmployeeCompetency with all schema-defined field rules.
pub fn employee_competency_validator() -> EmployeeCompetencyValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
