//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod competency_validator;
pub mod course_validator;
pub mod course_enrollment_validator;
pub mod employee_competency_validator;
pub mod employee_skill_validator;
pub mod skill_validator;

pub use competency_validator::{CompetencyValidator, competency_validator};
pub use course_validator::{CourseValidator, course_validator};
pub use course_enrollment_validator::{CourseEnrollmentValidator, course_enrollment_validator};
pub use employee_competency_validator::{EmployeeCompetencyValidator, employee_competency_validator};
pub use employee_skill_validator::{EmployeeSkillValidator, employee_skill_validator};
pub use skill_validator::{SkillValidator, skill_validator};

// <<< CUSTOM
// END CUSTOM
