//! Validator for Skill entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Skill>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Skill;

/// Validator type alias for Skill entities.
pub type SkillValidator = EntityValidator<Skill>;

/// Build a validator for Skill with all schema-defined field rules.
pub fn skill_validator() -> SkillValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Skill| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &Skill| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
