//! Auth configuration for Competency handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Competency>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CompetencyService;
use crate::domain::entity::Competency;

/// Permission string constants for Competency operations.
pub mod permissions {
    pub const LIST:        &str = "competency:list";
    pub const READ:        &str = "competency:read";
    pub const CREATE:      &str = "competency:create";
    pub const UPDATE:      &str = "competency:update";
    pub const DELETE:      &str = "competency:delete";
    pub const RESTORE:     &str = "competency:restore";
    pub const TRASH:       &str = "competency:trash";
    pub const EMPTY_TRASH: &str = "competency:empty_trash";
    pub const BULK_CREATE: &str = "competency:bulk_create";
    pub const UPSERT:      &str = "competency:upsert";
}

/// Resource policy for Competency — maps CRUD actions to permission strings.
pub struct CompetencyPolicy;

#[async_trait]
impl ResourcePolicy<Competency> for CompetencyPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Competency,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Competency handlers.
///
/// Wraps `CompetencyService` and checks `CompetencyPolicy` before delegating.
pub type CompetencyGuard = PermissionGuard<Competency>;

/// Service-integrated permission guard for Competency (for use in generated handlers).
pub type CompetencyServiceGuard = ServicePermissionGuard<Competency, CompetencyService, CompetencyPolicy>;

// <<< CUSTOM
// END CUSTOM
