//! Auth configuration for CourseEnrollment handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<CourseEnrollment>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CourseEnrollmentService;
use crate::domain::entity::CourseEnrollment;

/// Permission string constants for CourseEnrollment operations.
pub mod permissions {
    pub const LIST:        &str = "course_enrollment:list";
    pub const READ:        &str = "course_enrollment:read";
    pub const CREATE:      &str = "course_enrollment:create";
    pub const UPDATE:      &str = "course_enrollment:update";
    pub const DELETE:      &str = "course_enrollment:delete";
    pub const RESTORE:     &str = "course_enrollment:restore";
    pub const TRASH:       &str = "course_enrollment:trash";
    pub const EMPTY_TRASH: &str = "course_enrollment:empty_trash";
    pub const BULK_CREATE: &str = "course_enrollment:bulk_create";
    pub const UPSERT:      &str = "course_enrollment:upsert";
}

/// Resource policy for CourseEnrollment — maps CRUD actions to permission strings.
pub struct CourseEnrollmentPolicy;

#[async_trait]
impl ResourcePolicy<CourseEnrollment> for CourseEnrollmentPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &CourseEnrollment,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for CourseEnrollment handlers.
///
/// Wraps `CourseEnrollmentService` and checks `CourseEnrollmentPolicy` before delegating.
pub type CourseEnrollmentGuard = PermissionGuard<CourseEnrollment>;

/// Service-integrated permission guard for CourseEnrollment (for use in generated handlers).
pub type CourseEnrollmentServiceGuard = ServicePermissionGuard<CourseEnrollment, CourseEnrollmentService, CourseEnrollmentPolicy>;

// <<< CUSTOM
// END CUSTOM
