//! Auth configuration for Course handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Course>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CourseService;
use crate::domain::entity::Course;

/// Permission string constants for Course operations.
pub mod permissions {
    pub const LIST:        &str = "course:list";
    pub const READ:        &str = "course:read";
    pub const CREATE:      &str = "course:create";
    pub const UPDATE:      &str = "course:update";
    pub const DELETE:      &str = "course:delete";
    pub const RESTORE:     &str = "course:restore";
    pub const TRASH:       &str = "course:trash";
    pub const EMPTY_TRASH: &str = "course:empty_trash";
    pub const BULK_CREATE: &str = "course:bulk_create";
    pub const UPSERT:      &str = "course:upsert";
}

/// Resource policy for Course — maps CRUD actions to permission strings.
pub struct CoursePolicy;

#[async_trait]
impl ResourcePolicy<Course> for CoursePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Course,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Course handlers.
///
/// Wraps `CourseService` and checks `CoursePolicy` before delegating.
pub type CourseGuard = PermissionGuard<Course>;

/// Service-integrated permission guard for Course (for use in generated handlers).
pub type CourseServiceGuard = ServicePermissionGuard<Course, CourseService, CoursePolicy>;

// <<< CUSTOM
// END CUSTOM
