//! Auth configuration for EmployeeSkill handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<EmployeeSkill>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::EmployeeSkillService;
use crate::domain::entity::EmployeeSkill;

/// Permission string constants for EmployeeSkill operations.
pub mod permissions {
    pub const LIST:        &str = "employee_skill:list";
    pub const READ:        &str = "employee_skill:read";
    pub const CREATE:      &str = "employee_skill:create";
    pub const UPDATE:      &str = "employee_skill:update";
    pub const DELETE:      &str = "employee_skill:delete";
    pub const RESTORE:     &str = "employee_skill:restore";
    pub const TRASH:       &str = "employee_skill:trash";
    pub const EMPTY_TRASH: &str = "employee_skill:empty_trash";
    pub const BULK_CREATE: &str = "employee_skill:bulk_create";
    pub const UPSERT:      &str = "employee_skill:upsert";
}

/// Resource policy for EmployeeSkill — maps CRUD actions to permission strings.
pub struct EmployeeSkillPolicy;

#[async_trait]
impl ResourcePolicy<EmployeeSkill> for EmployeeSkillPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &EmployeeSkill,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for EmployeeSkill handlers.
///
/// Wraps `EmployeeSkillService` and checks `EmployeeSkillPolicy` before delegating.
pub type EmployeeSkillGuard = PermissionGuard<EmployeeSkill>;

/// Service-integrated permission guard for EmployeeSkill (for use in generated handlers).
pub type EmployeeSkillServiceGuard = ServicePermissionGuard<EmployeeSkill, EmployeeSkillService, EmployeeSkillPolicy>;

// <<< CUSTOM
// END CUSTOM
