//! Auth configuration for EmployeeCompetency handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<EmployeeCompetency>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::EmployeeCompetencyService;
use crate::domain::entity::EmployeeCompetency;

/// Permission string constants for EmployeeCompetency operations.
pub mod permissions {
    pub const LIST:        &str = "employee_competency:list";
    pub const READ:        &str = "employee_competency:read";
    pub const CREATE:      &str = "employee_competency:create";
    pub const UPDATE:      &str = "employee_competency:update";
    pub const DELETE:      &str = "employee_competency:delete";
    pub const RESTORE:     &str = "employee_competency:restore";
    pub const TRASH:       &str = "employee_competency:trash";
    pub const EMPTY_TRASH: &str = "employee_competency:empty_trash";
    pub const BULK_CREATE: &str = "employee_competency:bulk_create";
    pub const UPSERT:      &str = "employee_competency:upsert";
}

/// Resource policy for EmployeeCompetency — maps CRUD actions to permission strings.
pub struct EmployeeCompetencyPolicy;

#[async_trait]
impl ResourcePolicy<EmployeeCompetency> for EmployeeCompetencyPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &EmployeeCompetency,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for EmployeeCompetency handlers.
///
/// Wraps `EmployeeCompetencyService` and checks `EmployeeCompetencyPolicy` before delegating.
pub type EmployeeCompetencyGuard = PermissionGuard<EmployeeCompetency>;

/// Service-integrated permission guard for EmployeeCompetency (for use in generated handlers).
pub type EmployeeCompetencyServiceGuard = ServicePermissionGuard<EmployeeCompetency, EmployeeCompetencyService, EmployeeCompetencyPolicy>;

// <<< CUSTOM
// END CUSTOM
