//! Auth configuration for Skill handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Skill>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SkillService;
use crate::domain::entity::Skill;

/// Permission string constants for Skill operations.
pub mod permissions {
    pub const LIST:        &str = "skill:list";
    pub const READ:        &str = "skill:read";
    pub const CREATE:      &str = "skill:create";
    pub const UPDATE:      &str = "skill:update";
    pub const DELETE:      &str = "skill:delete";
    pub const RESTORE:     &str = "skill:restore";
    pub const TRASH:       &str = "skill:trash";
    pub const EMPTY_TRASH: &str = "skill:empty_trash";
    pub const BULK_CREATE: &str = "skill:bulk_create";
    pub const UPSERT:      &str = "skill:upsert";
}

/// Resource policy for Skill — maps CRUD actions to permission strings.
pub struct SkillPolicy;

#[async_trait]
impl ResourcePolicy<Skill> for SkillPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Skill,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Skill handlers.
///
/// Wraps `SkillService` and checks `SkillPolicy` before delegating.
pub type SkillGuard = PermissionGuard<Skill>;

/// Service-integrated permission guard for Skill (for use in generated handlers).
pub type SkillServiceGuard = ServicePermissionGuard<Skill, SkillService, SkillPolicy>;

// <<< CUSTOM
// END CUSTOM
