//! CourseEnrollment API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the CourseEnrollment CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// COURSEENROLLMENT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for CourseEnrollment
pub struct CourseEnrollmentTestData;

impl TestDataGenerator for CourseEnrollmentTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "course_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "status": "enrolled",
            "enrolled_at": now,
            "completed_at": now,
            "score": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "course_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "status": "enrolled",
            "enrolled_at": now,
            "completed_at": now,
            "score": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/courses", &super::course_api_test::CourseTestData).await {
            deps.push(("course_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// COURSEENROLLMENT API TEST
// ============================================================================

/// CourseEnrollment API test suite
pub struct CourseEnrollmentApiTest {
    inner: GenericCrudTest<CourseEnrollmentTestData>,
}

impl CourseEnrollmentApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/course_enrollments", "CourseEnrollment");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CourseEnrollmentTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CourseEnrollmentApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_course_enrollment_crud() {
        let mut test = CourseEnrollmentApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add CourseEnrollment specific tests here
// <<< CUSTOM TESTS END >>>
