//! EmployeeCompetency API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the EmployeeCompetency CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// EMPLOYEECOMPETENCY TEST DATA GENERATOR
// ============================================================================

/// Test data generator for EmployeeCompetency
pub struct EmployeeCompetencyTestData;

impl TestDataGenerator for EmployeeCompetencyTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "competency_id": Uuid::new_v4().to_string(),
            "level": 1,
            "assessed_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "employee_id": Uuid::new_v4().to_string(),
            "competency_id": Uuid::new_v4().to_string(),
            "level": 1,
            "assessed_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(
            api,
            "/api/v1/competencies",
            &super::competency_api_test::CompetencyTestData,
        )
        .await
        {
            deps.push(("competency_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// EMPLOYEECOMPETENCY API TEST
// ============================================================================

/// EmployeeCompetency API test suite
pub struct EmployeeCompetencyApiTest {
    inner: GenericCrudTest<EmployeeCompetencyTestData>,
}

impl EmployeeCompetencyApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/employee_competencies", "EmployeeCompetency");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, EmployeeCompetencyTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for EmployeeCompetencyApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_employee_competency_crud() {
        let mut test = EmployeeCompetencyApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add EmployeeCompetency specific tests here
// <<< CUSTOM TESTS END >>>
