//! EmployeeSkill API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the EmployeeSkill CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// EMPLOYEESKILL TEST DATA GENERATOR
// ============================================================================

/// Test data generator for EmployeeSkill
pub struct EmployeeSkillTestData;

impl TestDataGenerator for EmployeeSkillTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "skill_id": Uuid::new_v4().to_string(),
            "proficiency": "novice",
            "years_experience": null,
            "verification": "self_reported",
            "verified_by": null,
            "last_used_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "skill_id": Uuid::new_v4().to_string(),
            "proficiency": "novice",
            "years_experience": null,
            "verification": "self_reported",
            "verified_by": null,
            "last_used_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/skills", &super::skill_api_test::SkillTestData).await {
            deps.push(("skill_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// EMPLOYEESKILL API TEST
// ============================================================================

/// EmployeeSkill API test suite
pub struct EmployeeSkillApiTest {
    inner: GenericCrudTest<EmployeeSkillTestData>,
}

impl EmployeeSkillApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/employee_skills", "EmployeeSkill");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, EmployeeSkillTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for EmployeeSkillApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_employee_skill_crud() {
        let mut test = EmployeeSkillApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add EmployeeSkill specific tests here
// <<< CUSTOM TESTS END >>>
