//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod competency_api_test;
pub mod course_api_test;
pub mod course_enrollment_api_test;
pub mod employee_competency_api_test;
pub mod employee_skill_api_test;
pub mod skill_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use competency_api_test::*;
pub use course_api_test::*;
pub use course_enrollment_api_test::*;
pub use employee_competency_api_test::*;
pub use employee_skill_api_test::*;
pub use skill_api_test::*;
