//! Learning Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::CompetencyService;
use crate::application::service::CourseService;
use crate::application::service::CourseEnrollmentService;
use crate::application::service::EmployeeCompetencyService;
use crate::application::service::EmployeeSkillService;
use crate::application::service::SkillService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Competency service
    pub competency_service: Arc<CompetencyService>,
    /// Course service
    pub course_service: Arc<CourseService>,
    /// CourseEnrollment service
    pub course_enrollment_service: Arc<CourseEnrollmentService>,
    /// EmployeeCompetency service
    pub employee_competency_service: Arc<EmployeeCompetencyService>,
    /// EmployeeSkill service
    pub employee_skill_service: Arc<EmployeeSkillService>,
    /// Skill service
    pub skill_service: Arc<SkillService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        competency_service: Arc<CompetencyService>,
        course_service: Arc<CourseService>,
        course_enrollment_service: Arc<CourseEnrollmentService>,
        employee_competency_service: Arc<EmployeeCompetencyService>,
        employee_skill_service: Arc<EmployeeSkillService>,
        skill_service: Arc<SkillService>
    ) -> Self {
        Self {
            competency_service,
            course_service,
            course_enrollment_service,
            employee_competency_service,
            employee_skill_service,
            skill_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::LearningModule) -> Self {
        Self {
            competency_service: module.competency_service.clone(),
            course_service: module.course_service.clone(),
            course_enrollment_service: module.course_enrollment_service.clone(),
            employee_competency_service: module.employee_competency_service.clone(),
            employee_skill_service: module.employee_skill_service.clone(),
            skill_service: module.skill_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    competency_service: Option<Arc<CompetencyService>>,
    course_service: Option<Arc<CourseService>>,
    course_enrollment_service: Option<Arc<CourseEnrollmentService>>,
    employee_competency_service: Option<Arc<EmployeeCompetencyService>>,
    employee_skill_service: Option<Arc<EmployeeSkillService>>,
    skill_service: Option<Arc<SkillService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Competency service.
    pub fn with_competency_service(mut self, service: Arc<CompetencyService>) -> Self {
        self.competency_service = Some(service);
        self
    }

    /// Set the Course service.
    pub fn with_course_service(mut self, service: Arc<CourseService>) -> Self {
        self.course_service = Some(service);
        self
    }

    /// Set the CourseEnrollment service.
    pub fn with_course_enrollment_service(mut self, service: Arc<CourseEnrollmentService>) -> Self {
        self.course_enrollment_service = Some(service);
        self
    }

    /// Set the EmployeeCompetency service.
    pub fn with_employee_competency_service(mut self, service: Arc<EmployeeCompetencyService>) -> Self {
        self.employee_competency_service = Some(service);
        self
    }

    /// Set the EmployeeSkill service.
    pub fn with_employee_skill_service(mut self, service: Arc<EmployeeSkillService>) -> Self {
        self.employee_skill_service = Some(service);
        self
    }

    /// Set the Skill service.
    pub fn with_skill_service(mut self, service: Arc<SkillService>) -> Self {
        self.skill_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            competency_service: self.competency_service.expect("competency_service is required"),
            course_service: self.course_service.expect("course_service is required"),
            course_enrollment_service: self.course_enrollment_service.expect("course_enrollment_service is required"),
            employee_competency_service: self.employee_competency_service.expect("employee_competency_service is required"),
            employee_skill_service: self.employee_skill_service.expect("employee_skill_service is required"),
            skill_service: self.skill_service.expect("skill_service is required"),
        }
    }
}
