//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    competency_handler::create_competency_routes,
    course_handler::create_course_routes,
    course_enrollment_handler::create_course_enrollment_routes,
    employee_competency_handler::create_employee_competency_routes,
    employee_skill_handler::create_employee_skill_routes,
    skill_handler::create_skill_routes,
};

use crate::application::service::{
    CompetencyService,
    CourseService,
    CourseEnrollmentService,
    EmployeeCompetencyService,
    EmployeeSkillService,
    SkillService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub competency: Arc<CompetencyService>,
    pub course: Arc<CourseService>,
    pub course_enrollment: Arc<CourseEnrollmentService>,
    pub employee_competency: Arc<EmployeeCompetencyService>,
    pub employee_skill: Arc<EmployeeSkillService>,
    pub skill: Arc<SkillService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Competency routes (12 Backbone endpoints)
        .merge(create_competency_routes(services.competency))
        // Course routes (12 Backbone endpoints)
        .merge(create_course_routes(services.course))
        // CourseEnrollment routes (12 Backbone endpoints)
        .merge(create_course_enrollment_routes(services.course_enrollment))
        // EmployeeCompetency routes (12 Backbone endpoints)
        .merge(create_employee_competency_routes(services.employee_competency))
        // EmployeeSkill routes (12 Backbone endpoints)
        .merge(create_employee_skill_routes(services.employee_skill))
        // Skill routes (12 Backbone endpoints)
        .merge(create_skill_routes(services.skill))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn competency_routes(service: Arc<CompetencyService>) -> Router {
        create_competency_routes(service)
    }

    pub fn course_routes(service: Arc<CourseService>) -> Router {
        create_course_routes(service)
    }

    pub fn course_enrollment_routes(service: Arc<CourseEnrollmentService>) -> Router {
        create_course_enrollment_routes(service)
    }

    pub fn employee_competency_routes(service: Arc<EmployeeCompetencyService>) -> Router {
        create_employee_competency_routes(service)
    }

    pub fn employee_skill_routes(service: Arc<EmployeeSkillService>) -> Router {
        create_employee_skill_routes(service)
    }

    pub fn skill_routes(service: Arc<SkillService>) -> Router {
        create_skill_routes(service)
    }

}
