//! Public events for Learning module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// COMPETENCY EVENTS
// ============================================================================

/// Event published when a Competency is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompetencyCreatedEvent {
    pub id: CompetencyId,
    pub data: CompetencyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Competency is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompetencyUpdatedEvent {
    pub id: CompetencyId,
    pub data: CompetencyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Competency is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompetencyDeletedEvent {
    pub id: CompetencyId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// COURSE EVENTS
// ============================================================================

/// Event published when a Course is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CourseCreatedEvent {
    pub id: CourseId,
    pub data: CourseDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Course is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CourseUpdatedEvent {
    pub id: CourseId,
    pub data: CourseDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Course is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CourseDeletedEvent {
    pub id: CourseId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// COURSEENROLLMENT EVENTS
// ============================================================================

/// Event published when a CourseEnrollment is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CourseEnrollmentCreatedEvent {
    pub id: CourseEnrollmentId,
    pub data: CourseEnrollmentDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CourseEnrollment is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CourseEnrollmentUpdatedEvent {
    pub id: CourseEnrollmentId,
    pub data: CourseEnrollmentDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a CourseEnrollment is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CourseEnrollmentDeletedEvent {
    pub id: CourseEnrollmentId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// EMPLOYEECOMPETENCY EVENTS
// ============================================================================

/// Event published when a EmployeeCompetency is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeCompetencyCreatedEvent {
    pub id: EmployeeCompetencyId,
    pub data: EmployeeCompetencyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a EmployeeCompetency is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeCompetencyUpdatedEvent {
    pub id: EmployeeCompetencyId,
    pub data: EmployeeCompetencyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a EmployeeCompetency is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeCompetencyDeletedEvent {
    pub id: EmployeeCompetencyId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// EMPLOYEESKILL EVENTS
// ============================================================================

/// Event published when a EmployeeSkill is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeSkillCreatedEvent {
    pub id: EmployeeSkillId,
    pub data: EmployeeSkillDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a EmployeeSkill is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeSkillUpdatedEvent {
    pub id: EmployeeSkillId,
    pub data: EmployeeSkillDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a EmployeeSkill is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeSkillDeletedEvent {
    pub id: EmployeeSkillId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SKILL EVENTS
// ============================================================================

/// Event published when a Skill is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillCreatedEvent {
    pub id: SkillId,
    pub data: SkillDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Skill is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillUpdatedEvent {
    pub id: SkillId,
    pub data: SkillDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Skill is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillDeletedEvent {
    pub id: SkillId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Learning module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum LearningEvent {
    CompetencyCreated(CompetencyCreatedEvent),
    CompetencyUpdated(CompetencyUpdatedEvent),
    CompetencyDeleted(CompetencyDeletedEvent),
    CourseCreated(CourseCreatedEvent),
    CourseUpdated(CourseUpdatedEvent),
    CourseDeleted(CourseDeletedEvent),
    CourseEnrollmentCreated(CourseEnrollmentCreatedEvent),
    CourseEnrollmentUpdated(CourseEnrollmentUpdatedEvent),
    CourseEnrollmentDeleted(CourseEnrollmentDeletedEvent),
    EmployeeCompetencyCreated(EmployeeCompetencyCreatedEvent),
    EmployeeCompetencyUpdated(EmployeeCompetencyUpdatedEvent),
    EmployeeCompetencyDeleted(EmployeeCompetencyDeletedEvent),
    EmployeeSkillCreated(EmployeeSkillCreatedEvent),
    EmployeeSkillUpdated(EmployeeSkillUpdatedEvent),
    EmployeeSkillDeleted(EmployeeSkillDeletedEvent),
    SkillCreated(SkillCreatedEvent),
    SkillUpdated(SkillUpdatedEvent),
    SkillDeleted(SkillDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LearningEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for LearningEventMetadata {
    fn default() -> Self {
        Self {
            module: "learning",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
