//! Learning Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Learning exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use learning::exports::{CompetencyDto, LearningQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `CompetencyDto` - Data transfer object for Competency
/// - `CompetencySummary` - Summary view of Competency
/// - `CompetencyId` - Type-safe ID wrapper
/// - `CourseDto` - Data transfer object for Course
/// - `CourseSummary` - Summary view of Course
/// - `CourseId` - Type-safe ID wrapper
/// - `CourseEnrollmentDto` - Data transfer object for CourseEnrollment
/// - `CourseEnrollmentSummary` - Summary view of CourseEnrollment
/// - `CourseEnrollmentId` - Type-safe ID wrapper
/// - `EmployeeCompetencyDto` - Data transfer object for EmployeeCompetency
/// - `EmployeeCompetencySummary` - Summary view of EmployeeCompetency
/// - `EmployeeCompetencyId` - Type-safe ID wrapper
/// - `EmployeeSkillDto` - Data transfer object for EmployeeSkill
/// - `EmployeeSkillSummary` - Summary view of EmployeeSkill
/// - `EmployeeSkillId` - Type-safe ID wrapper
/// - `SkillDto` - Data transfer object for Skill
/// - `SkillSummary` - Summary view of Skill
/// - `SkillId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `LearningQueryService` - Read-only queries
///
/// ## Public Events
/// - `CompetencyCreatedEvent` - Published when Competency is created
/// - `CompetencyUpdatedEvent` - Published when Competency is updated
/// - `CompetencyDeletedEvent` - Published when Competency is deleted
/// - `CourseCreatedEvent` - Published when Course is created
/// - `CourseUpdatedEvent` - Published when Course is updated
/// - `CourseDeletedEvent` - Published when Course is deleted
/// - `CourseEnrollmentCreatedEvent` - Published when CourseEnrollment is created
/// - `CourseEnrollmentUpdatedEvent` - Published when CourseEnrollment is updated
/// - `CourseEnrollmentDeletedEvent` - Published when CourseEnrollment is deleted
/// - `EmployeeCompetencyCreatedEvent` - Published when EmployeeCompetency is created
/// - `EmployeeCompetencyUpdatedEvent` - Published when EmployeeCompetency is updated
/// - `EmployeeCompetencyDeletedEvent` - Published when EmployeeCompetency is deleted
/// - `EmployeeSkillCreatedEvent` - Published when EmployeeSkill is created
/// - `EmployeeSkillUpdatedEvent` - Published when EmployeeSkill is updated
/// - `EmployeeSkillDeletedEvent` - Published when EmployeeSkill is deleted
/// - `SkillCreatedEvent` - Published when Skill is created
/// - `SkillUpdatedEvent` - Published when Skill is updated
/// - `SkillDeletedEvent` - Published when Skill is deleted
pub struct ExportSummary;
