//! Public services for Learning module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Learning module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait LearningQueryService: Send + Sync {
    /// Get Competency by ID
    async fn get_competency(&self, id: CompetencyId) -> Result<Option<CompetencyDto>>;

    /// Get Competency summary by ID
    async fn get_competency_summary(&self, id: CompetencyId) -> Result<Option<CompetencySummary>>;

    /// Check if Competency exists
    async fn competency_exists(&self, id: CompetencyId) -> Result<bool>;

    /// Get Course by ID
    async fn get_course(&self, id: CourseId) -> Result<Option<CourseDto>>;

    /// Get Course summary by ID
    async fn get_course_summary(&self, id: CourseId) -> Result<Option<CourseSummary>>;

    /// Check if Course exists
    async fn course_exists(&self, id: CourseId) -> Result<bool>;

    /// Get CourseEnrollment by ID
    async fn get_course_enrollment(&self, id: CourseEnrollmentId) -> Result<Option<CourseEnrollmentDto>>;

    /// Get CourseEnrollment summary by ID
    async fn get_course_enrollment_summary(&self, id: CourseEnrollmentId) -> Result<Option<CourseEnrollmentSummary>>;

    /// Check if CourseEnrollment exists
    async fn course_enrollment_exists(&self, id: CourseEnrollmentId) -> Result<bool>;

    /// Get EmployeeCompetency by ID
    async fn get_employee_competency(&self, id: EmployeeCompetencyId) -> Result<Option<EmployeeCompetencyDto>>;

    /// Get EmployeeCompetency summary by ID
    async fn get_employee_competency_summary(&self, id: EmployeeCompetencyId) -> Result<Option<EmployeeCompetencySummary>>;

    /// Check if EmployeeCompetency exists
    async fn employee_competency_exists(&self, id: EmployeeCompetencyId) -> Result<bool>;

    /// Get EmployeeSkill by ID
    async fn get_employee_skill(&self, id: EmployeeSkillId) -> Result<Option<EmployeeSkillDto>>;

    /// Get EmployeeSkill summary by ID
    async fn get_employee_skill_summary(&self, id: EmployeeSkillId) -> Result<Option<EmployeeSkillSummary>>;

    /// Check if EmployeeSkill exists
    async fn employee_skill_exists(&self, id: EmployeeSkillId) -> Result<bool>;

    /// Get Skill by ID
    async fn get_skill(&self, id: SkillId) -> Result<Option<SkillDto>>;

    /// Get Skill summary by ID
    async fn get_skill_summary(&self, id: SkillId) -> Result<Option<SkillSummary>>;

    /// Check if Skill exists
    async fn skill_exists(&self, id: SkillId) -> Result<bool>;

}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
