//! Public types for Learning module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// COMPETENCY TYPES
// ============================================================================

/// Type-safe ID for Competency
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CompetencyId(pub Uuid);

impl CompetencyId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CompetencyId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CompetencyId> for Uuid {
    fn from(id: CompetencyId) -> Self {
        id.0
    }
}

/// Data transfer object for Competency
///
/// This is the public representation of Competency for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompetencyDto {
    pub id: CompetencyId,
    pub company_id: Uuid,
    pub name: String,
    pub category: Option<CompetencyCategory>,
    pub description: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of Competency for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompetencySummary {
    pub id: CompetencyId,
    pub name: String,
}

/// Reference to Competency for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompetencyRef {
    pub id: CompetencyId,
}

// ============================================================================
// COURSE TYPES
// ============================================================================

/// Type-safe ID for Course
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CourseId(pub Uuid);

impl CourseId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CourseId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CourseId> for Uuid {
    fn from(id: CourseId) -> Self {
        id.0
    }
}

/// Data transfer object for Course
///
/// This is the public representation of Course for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CourseDto {
    pub id: CourseId,
    pub company_id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub format: CourseFormat,
    pub duration_hours: Option<Decimal>,
    pub cost: Option<Decimal>,
    pub provider: Option<String>,
    pub certification_id: Option<Uuid>,
    pub is_active: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of Course for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CourseSummary {
    pub id: CourseId,
    pub name: String,
}

/// Reference to Course for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CourseRef {
    pub id: CourseId,
}

// ============================================================================
// COURSEENROLLMENT TYPES
// ============================================================================

/// Type-safe ID for CourseEnrollment
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CourseEnrollmentId(pub Uuid);

impl CourseEnrollmentId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CourseEnrollmentId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CourseEnrollmentId> for Uuid {
    fn from(id: CourseEnrollmentId) -> Self {
        id.0
    }
}

/// Data transfer object for CourseEnrollment
///
/// This is the public representation of CourseEnrollment for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CourseEnrollmentDto {
    pub id: CourseEnrollmentId,
    pub company_id: Uuid,
    pub course_id: Uuid,
    pub employee_id: Uuid,
    pub status: EnrollmentStatus,
    pub enrolled_at: NaiveDate,
    pub completed_at: Option<NaiveDate>,
    pub score: Option<Decimal>,
    pub metadata: serde_json::Value,
}

/// Summary view of CourseEnrollment for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CourseEnrollmentSummary {
    pub id: CourseEnrollmentId,
    pub status: EnrollmentStatus,
}

/// Reference to CourseEnrollment for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CourseEnrollmentRef {
    pub id: CourseEnrollmentId,
}

// ============================================================================
// EMPLOYEECOMPETENCY TYPES
// ============================================================================

/// Type-safe ID for EmployeeCompetency
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EmployeeCompetencyId(pub Uuid);

impl EmployeeCompetencyId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EmployeeCompetencyId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EmployeeCompetencyId> for Uuid {
    fn from(id: EmployeeCompetencyId) -> Self {
        id.0
    }
}

/// Data transfer object for EmployeeCompetency
///
/// This is the public representation of EmployeeCompetency for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeCompetencyDto {
    pub id: EmployeeCompetencyId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub competency_id: Uuid,
    pub level: i32,
    pub assessed_at: Option<NaiveDate>,
    pub metadata: serde_json::Value,
}

/// Summary view of EmployeeCompetency for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeCompetencySummary {
    pub id: EmployeeCompetencyId,
}

/// Reference to EmployeeCompetency for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeCompetencyRef {
    pub id: EmployeeCompetencyId,
}

// ============================================================================
// EMPLOYEESKILL TYPES
// ============================================================================

/// Type-safe ID for EmployeeSkill
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EmployeeSkillId(pub Uuid);

impl EmployeeSkillId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for EmployeeSkillId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<EmployeeSkillId> for Uuid {
    fn from(id: EmployeeSkillId) -> Self {
        id.0
    }
}

/// Data transfer object for EmployeeSkill
///
/// This is the public representation of EmployeeSkill for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeSkillDto {
    pub id: EmployeeSkillId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub skill_id: Uuid,
    pub proficiency: ProficiencyLevel,
    pub years_experience: Option<Decimal>,
    pub verification: SkillVerification,
    pub verified_by: Option<Uuid>,
    pub last_used_at: Option<NaiveDate>,
    pub metadata: serde_json::Value,
}

/// Summary view of EmployeeSkill for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeSkillSummary {
    pub id: EmployeeSkillId,
}

/// Reference to EmployeeSkill for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeSkillRef {
    pub id: EmployeeSkillId,
}

// ============================================================================
// SKILL TYPES
// ============================================================================

/// Type-safe ID for Skill
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SkillId(pub Uuid);

impl SkillId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SkillId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SkillId> for Uuid {
    fn from(id: SkillId) -> Self {
        id.0
    }
}

/// Data transfer object for Skill
///
/// This is the public representation of Skill for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillDto {
    pub id: SkillId,
    pub company_id: Uuid,
    pub name: String,
    pub category: Option<SkillCategory>,
    pub description: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of Skill for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillSummary {
    pub id: SkillId,
    pub name: String,
}

/// Reference to Skill for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillRef {
    pub id: SkillId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
