//! Learning Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::CompetencyService;
pub use application::service::CourseService;
pub use application::service::CourseEnrollmentService;
pub use application::service::EmployeeCompetencyService;
pub use application::service::EmployeeSkillService;
pub use application::service::SkillService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Learning module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let learning = LearningModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = learning.all_crud_routes();
/// ```
pub struct LearningModule {
    pub(crate) competency_service: Arc<CompetencyService>,
    pub(crate) course_service: Arc<CourseService>,
    pub(crate) course_enrollment_service: Arc<CourseEnrollmentService>,
    pub(crate) employee_competency_service: Arc<EmployeeCompetencyService>,
    pub(crate) employee_skill_service: Arc<EmployeeSkillService>,
    pub(crate) skill_service: Arc<SkillService>,
    // <<< CUSTOM FIELDS
    // END CUSTOM
}

impl LearningModule {
    /// Create a new module builder
    pub fn builder() -> LearningModuleBuilder {
        LearningModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_competency_routes,
            create_course_routes,
            create_course_enrollment_routes,
            create_employee_competency_routes,
            create_employee_skill_routes,
            create_skill_routes,
        };

        Router::new()
            .merge(create_competency_routes(self.competency_service.clone()))
            .merge(create_course_routes(self.course_service.clone()))
            .merge(create_course_enrollment_routes(self.course_enrollment_service.clone()))
            .merge(create_employee_competency_routes(self.employee_competency_service.clone()))
            .merge(create_employee_skill_routes(self.employee_skill_service.clone()))
            .merge(create_skill_routes(self.skill_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for LearningModule
pub struct LearningModuleBuilder {
    db_pool: Option<PgPool>,
}

impl LearningModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<LearningModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Competency service
        let competency_repository = Arc::new(CompetencyRepository::new(db_pool.clone()));
        let competency_service = Arc::new(CompetencyService::with_repository(competency_repository.clone()));

        // Course service
        let course_repository = Arc::new(CourseRepository::new(db_pool.clone()));
        let course_service = Arc::new(CourseService::with_repository(course_repository.clone()));

        // CourseEnrollment service
        let course_enrollment_repository = Arc::new(CourseEnrollmentRepository::new(db_pool.clone()));
        let course_enrollment_service = Arc::new(CourseEnrollmentService::with_repository(course_enrollment_repository.clone()));

        // EmployeeCompetency service
        let employee_competency_repository = Arc::new(EmployeeCompetencyRepository::new(db_pool.clone()));
        let employee_competency_service = Arc::new(EmployeeCompetencyService::with_repository(employee_competency_repository.clone()));

        // EmployeeSkill service
        let employee_skill_repository = Arc::new(EmployeeSkillRepository::new(db_pool.clone()));
        let employee_skill_service = Arc::new(EmployeeSkillService::with_repository(employee_skill_repository.clone()));

        // Skill service
        let skill_repository = Arc::new(SkillRepository::new(db_pool.clone()));
        let skill_service = Arc::new(SkillService::with_repository(skill_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(LearningModule {
            competency_service,
            course_service,
            course_enrollment_service,
            employee_competency_service,
            employee_skill_service,
            skill_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for LearningModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
