//! Use case type aliases for Competency aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCompetencyDto, UpdateCompetencyDto};
use crate::application::service::CompetencyService;
use crate::domain::entity::Competency;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCompetencyUseCase = CreateUseCase<Competency, CreateCompetencyDto, CompetencyService>;
pub type UpdateCompetencyUseCase = UpdateUseCase<Competency, UpdateCompetencyDto, CompetencyService>;
pub type GetCompetencyUseCase    = GetUseCase<Competency, CompetencyService>;
pub type DeleteCompetencyUseCase = DeleteUseCase<Competency, CompetencyService>;
pub type ListCompetencyUseCase   = ListUseCase<Competency, CompetencyService>;

// <<< CUSTOM
// END CUSTOM
