//! Use case type aliases for Course aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCourseDto, UpdateCourseDto};
use crate::application::service::CourseService;
use crate::domain::entity::Course;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCourseUseCase = CreateUseCase<Course, CreateCourseDto, CourseService>;
pub type UpdateCourseUseCase = UpdateUseCase<Course, UpdateCourseDto, CourseService>;
pub type GetCourseUseCase    = GetUseCase<Course, CourseService>;
pub type DeleteCourseUseCase = DeleteUseCase<Course, CourseService>;
pub type ListCourseUseCase   = ListUseCase<Course, CourseService>;

// <<< CUSTOM
// END CUSTOM
