//! Use case type aliases for CourseEnrollment aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCourseEnrollmentDto, UpdateCourseEnrollmentDto};
use crate::application::service::CourseEnrollmentService;
use crate::domain::entity::CourseEnrollment;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCourseEnrollmentUseCase = CreateUseCase<CourseEnrollment, CreateCourseEnrollmentDto, CourseEnrollmentService>;
pub type UpdateCourseEnrollmentUseCase = UpdateUseCase<CourseEnrollment, UpdateCourseEnrollmentDto, CourseEnrollmentService>;
pub type GetCourseEnrollmentUseCase    = GetUseCase<CourseEnrollment, CourseEnrollmentService>;
pub type DeleteCourseEnrollmentUseCase = DeleteUseCase<CourseEnrollment, CourseEnrollmentService>;
pub type ListCourseEnrollmentUseCase   = ListUseCase<CourseEnrollment, CourseEnrollmentService>;

// <<< CUSTOM
// END CUSTOM
