//! Use case type aliases for EmployeeCompetency aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateEmployeeCompetencyDto, UpdateEmployeeCompetencyDto};
use crate::application::service::EmployeeCompetencyService;
use crate::domain::entity::EmployeeCompetency;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateEmployeeCompetencyUseCase = CreateUseCase<EmployeeCompetency, CreateEmployeeCompetencyDto, EmployeeCompetencyService>;
pub type UpdateEmployeeCompetencyUseCase = UpdateUseCase<EmployeeCompetency, UpdateEmployeeCompetencyDto, EmployeeCompetencyService>;
pub type GetEmployeeCompetencyUseCase    = GetUseCase<EmployeeCompetency, EmployeeCompetencyService>;
pub type DeleteEmployeeCompetencyUseCase = DeleteUseCase<EmployeeCompetency, EmployeeCompetencyService>;
pub type ListEmployeeCompetencyUseCase   = ListUseCase<EmployeeCompetency, EmployeeCompetencyService>;

// <<< CUSTOM
// END CUSTOM
