//! Use case type aliases for EmployeeSkill aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateEmployeeSkillDto, UpdateEmployeeSkillDto};
use crate::application::service::EmployeeSkillService;
use crate::domain::entity::EmployeeSkill;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateEmployeeSkillUseCase = CreateUseCase<EmployeeSkill, CreateEmployeeSkillDto, EmployeeSkillService>;
pub type UpdateEmployeeSkillUseCase = UpdateUseCase<EmployeeSkill, UpdateEmployeeSkillDto, EmployeeSkillService>;
pub type GetEmployeeSkillUseCase    = GetUseCase<EmployeeSkill, EmployeeSkillService>;
pub type DeleteEmployeeSkillUseCase = DeleteUseCase<EmployeeSkill, EmployeeSkillService>;
pub type ListEmployeeSkillUseCase   = ListUseCase<EmployeeSkill, EmployeeSkillService>;

// <<< CUSTOM
// END CUSTOM
