//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod competency_usecases;
pub mod course_usecases;
pub mod course_enrollment_usecases;
pub mod employee_competency_usecases;
pub mod employee_skill_usecases;
pub mod skill_usecases;

pub use competency_usecases::{
    CreateCompetencyUseCase, UpdateCompetencyUseCase, GetCompetencyUseCase,
    DeleteCompetencyUseCase, ListCompetencyUseCase,
};
pub use course_usecases::{
    CreateCourseUseCase, UpdateCourseUseCase, GetCourseUseCase,
    DeleteCourseUseCase, ListCourseUseCase,
};
pub use course_enrollment_usecases::{
    CreateCourseEnrollmentUseCase, UpdateCourseEnrollmentUseCase, GetCourseEnrollmentUseCase,
    DeleteCourseEnrollmentUseCase, ListCourseEnrollmentUseCase,
};
pub use employee_competency_usecases::{
    CreateEmployeeCompetencyUseCase, UpdateEmployeeCompetencyUseCase, GetEmployeeCompetencyUseCase,
    DeleteEmployeeCompetencyUseCase, ListEmployeeCompetencyUseCase,
};
pub use employee_skill_usecases::{
    CreateEmployeeSkillUseCase, UpdateEmployeeSkillUseCase, GetEmployeeSkillUseCase,
    DeleteEmployeeSkillUseCase, ListEmployeeSkillUseCase,
};
pub use skill_usecases::{
    CreateSkillUseCase, UpdateSkillUseCase, GetSkillUseCase,
    DeleteSkillUseCase, ListSkillUseCase,
};

// <<< CUSTOM
// END CUSTOM
