//! Use case type aliases for Skill aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateSkillDto, UpdateSkillDto};
use crate::application::service::SkillService;
use crate::domain::entity::Skill;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateSkillUseCase = CreateUseCase<Skill, CreateSkillDto, SkillService>;
pub type UpdateSkillUseCase = UpdateUseCase<Skill, UpdateSkillDto, SkillService>;
pub type GetSkillUseCase    = GetUseCase<Skill, SkillService>;
pub type DeleteSkillUseCase = DeleteUseCase<Skill, SkillService>;
pub type ListSkillUseCase   = ListUseCase<Skill, SkillService>;

// <<< CUSTOM
// END CUSTOM
