//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod competency_handler;
pub mod course_handler;
pub mod course_enrollment_handler;
pub mod employee_competency_handler;
pub mod employee_skill_handler;
pub mod skill_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use competency_handler::{create_competency_routes, create_competency_read_routes, create_competency_write_routes};
pub use course_handler::{create_course_routes, create_course_read_routes, create_course_write_routes};
pub use course_enrollment_handler::{create_course_enrollment_routes, create_course_enrollment_read_routes, create_course_enrollment_write_routes};
pub use employee_competency_handler::{create_employee_competency_routes, create_employee_competency_read_routes, create_employee_competency_write_routes};
pub use employee_skill_handler::{create_employee_skill_routes, create_employee_skill_read_routes, create_employee_skill_write_routes};
pub use skill_handler::{create_skill_routes, create_skill_read_routes, create_skill_write_routes};
// <<< CUSTOM
// END CUSTOM
